### PR TITLE
Cache Component

### PR DESCRIPTION
**Pull request by hskrasek**
Adding the cache component. @mattstauffer do you want another driver done? Something like redis or memcache would require those services to be running locally if you wanted to test them in the browser.

Signed-off-by: Hunter Skrasek <hunterskrasek@me.com>

### CODE REVIEW

**Comment by mattstauffer** [comment]
:+1: Thanks @hskrasek !!

**Comment by hskrasek** [comment]
@mattstauffer did you want me to add an example of the other drivers? Or is it fine with just the file driver?

**Comment by jamescarlos** [comment]
@hskrasek @mattstauffer - i think it would be awesome to see other driver examples.

**Comment by mattstauffer** [comment]
@hskrasek yah, maybe as a different route?

**Comment by hskrasek** [comment]
@mattstauffer That was the plan. the only issue is that I have to make some assumptions on where the examples are being ran. Not everyone has redis running on their machine for example.

I'll open a new PR with the additional examples and we can decide how to handle that there

**Pull request merged**
